---
- name: Prepare
  hosts: all
  vars:
    git_dependencies:
      - git
    git_repo_path: /role_test

  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        name: "{{ git_dependencies }}"
        update_cache: true

    - name: Ensure test repository exists
      ansible.builtin.file:
        group: root
        mode: 0755
        owner: root
        path: "{{ git_repo_path }}"
        state: directory

    - name: Init test repository
      ansible.builtin.command: git init  # noqa command-instead-of-module
      args:
        chdir: "{{ git_repo_path }}"
        creates: .git
